---
title: Locating Creative Agency in Archaeological Data Work
author:
  - name: Zachary Batist
    id: zb
    url: https://zackbatist.info
    email: zachary.batist@mcgill.ca
    corresponding: true
    affiliations:
      - name: McGill University
        department: Epidemiology, Biostatistics and Occupational Health
        city: Montreal
        region: Quebec
    orcid: 0000-0003-0435-508X
date: today
abstract: |
  The workflows that are now commonplace across archaeological projects mask social and epistemic structures and principles.
  More specifically, they re-distribute creative agency to promote specific kinds of outcomes based on discrete data models.
  This paper draws attention to the mechanisms through which data are created and curated, focusing on the social and technical apparatus through which archaeologists control the creation and flow of information.
  Based on observations of and elicitations about archaeological data work in fieldwork settings at two cases, I articulate how the management of data and of labour are inherently intertwined, and how workflows are operationalized by managerial systems to ensure that data are created and curated toward productive ends.
keywords:
  - data work
  - information infrastructures
  - digital fieldwork practices
license: CC BY
citation:
  title: Locating Creative Agency in Archaeological Data Work
  url: https://zackbatist.info/locating-creative-agency.html
bibliography: /Users/zackbatist/Library/CloudStorage/Dropbox/zotero/zack.bib
csl: chicago-author-date.csl
toc: true
toc-depth: 3
toc-expand: 2
number-sections: false
format:
  html:
    page-layout: article
    embed-resources: true
    grid: 
      body-width: 1500px
---


{{< include sections/01_introduction.qmd >}}
{{< include sections/02_background.qmd >}}
{{< include sections/03_methods-materials.qmd >}}
{{< include sections/04_observations.qmd >}}
{{< include sections/05_discussion-conclusion.qmd >}}
{{< include sections/11_supplement-a.qmd >}}
{{< include sections/12_supplement-b.qmd >}}
{{< include sections/13_peer-reviews.qmd >}}

# Acknowledgments {.appendix}
I extend warm thanks to Costis Dallas, Matt Ratto, Ted Banning, Jeremy Huggett and Ed Swenson for supervising my work and providing critical feedback as I conducted my doctoral research, which this paper is based upon.
I am also very grateful to the anonymous reviewers for their constructive evaluation.
Of course, this work would not have been possible without the anonymous research participants who allowed me to observe and interview them as they worked, and to articulate their actions and outlooks.

# Funding {.appendix}
This work is derived from the author's doctoral dissertation, _Archaeological data work as continuous and collaborative practice_ [@batist2023a], which was supported by the Canadian Social Sciences and Humanities Research Council Doctoral Fellowship (Award ID: 752-2019-2233).

# Competing Interests {.appendix}
The author states no conflicts of interest.

# Author Contribution {.appendix}
Zachary Batist is the sole author of this work.
He defined the scope of the study and identified suitable cases for inclusion, collected and processed all data, performed analysis, interpreted the findings, created all the figures, and wrote the paper.

# Informed Consent {.appendix}
Informed consent has been obtained from all individuals included in this study, in compliance with the University of Toronto's Social Sciences, Humanities, and Education Research Ethics Board, Protocol 34526.

# Data Availability Statement {.appendix}
The data generated and analyzed during the current study are included in this published article's supplementary files.

# Author Bio {.appendix}
Zachary Batist obtained his PhD from the University of Toronto's Faculty of Information.
His research explores the collaborative commitments inherent throughout archaeological practice, especially relating to data management and the constitution of information commons.
He currently works as a Postdoctoral Researcher at the Department of Epidemiology, Biostatistics and Occupational Health in the School of Public and Global Health at McGill University, where he investigates the collaborative, technical and administrative structures that scaffold data harmonization in epidemiological research.
