# Background
I consider data as mediating devices that support research by connecting experiences distributed across time, place and community.
Data work therefore comprises acts of collaboration, or means of communicating varied archaeological encounters among invested stakeholders.
In other words, I conceive data work, which is omnipresent in all aspects of archaeological research, as the transformation of meanings from one set of activities to another via the materialization of information objects, such as recording sheets, reports, diagrams, finds bags, tags, scrap notes, descriptive monologues, stories, demonstrations, among many other entities exhibiting various degrees of tangibility and stability.

As with all acts of communication, archaeologists who work with data must reconcile the circumstances under which the data were created with the potential outcomes that they desire and deem feasible to achieve through them.
As such, working with data involves participating as part of a continuum of practice, whereby one's work is impacted by prior actions and has the potential to influence future outcomes [@dallas2015: 190].
I frame these connections as collaborative commitments, which govern professional relations among members of research communities, and which contribute to systemic norms regarding what data are and how they should be valued.
This suits my interest in articulating the ways in which expressions of archaeological meaning are valued and how archaeologists actively create information objects that exhibit such value.

This has implications for how we think about archaeological collaboration both within and between project collectives, and helps account for the problematic roll-out of open data infrastructures, particularly their lack of actual meaningful use [@huggett2018].
Archaeologists' struggle to reconcile prior decisions made in the creation and curation of data with their own secondary use cases is extremely visible in contexts of data reuse at distance from the data's origins, [@faniel2013: 299-301; @atici2013: 676-677; @kansa2013: 90-91; @chapman2016: 213; @austin2024], but similar dissonance also occurs _within_ projects, as archaeologists attempt to impose discrete structure on data emerging from improvised and situated experiences [cf. @khazraee2013; @haciguzeller2021; @batist2021; @huggett2022a: 276-278; @batist2023a].
My main goal in this section is to draw attention to prior work that addresses how infrastructures and organizational systems inform data collection within projects, especially in fieldwork settings, which are the primary loci of my analysis.
I highlight prior theoretical work on the nature and value of archaeological data, including commentary on contexts of initial archaeological encounters and how data are then picked up and applied in alternative analytical settings.

## Collection and capture
In the context of fieldwork,  which is where archaeologists tend to first encounter archaeological objects [@carver2010: 36], data are said to be "collected" [@petrosyan2021: 234; @buccellati2017], which implies that archaeologists are responsible for finding objects that exist in a relatively wild or unobserved state, and retrieving them for further study in more ordered and structured research environments.
This is concordant with the notion of "raw" data, which refers to observations made at the moment of the archaeological encounter, before being processed or modified in ways that are thought to add interpretive baggage [@huggett2022: 281].

Some critical perspectives more readily acknowledge the roles that archaeologists play in the creation of the archaeological record, rather than as those who merely document materials whose meanings are singular and fixed by the phenomena that generated them.
@chippindale2000 notably proposed re-framing "data" as "capta" to account for the pragmatic and motivated experience of obtaining information.
@drucker2011 supported this notion in stating that "data are capta, taken not given, constructed as an interpretation of the phenomenal world, not inherent in it," and @huggett2022 [: 276] summarized that, from a capta perspective, "data are not the start of the process but a consequence of multiple decisions, pre-determinations, and perspectives which precede the moment of capture and impose constraints on the observations recorded as data."
Similarly, @banning2020 [: 5-6] draws attention to the fact that archaeological data are products of human decisions and biases, and that their qualities, which bear traces of the pragmatic circumstances and potential value imagined by their creators, influence what can be done with them.

Numerous studies of archaeological practice have explored this perspective by explicitly situating archaeological data as aspects of social systems rife with complex power dynamics.
For instance, Gero [-@gero1985; -@gero1996], @politis2001, @wylie2003 and @mickel2021 examined gendered and neocolonial aspects of recording practices, which affect how records produced by women and racialized individuals are constructed and valued.
@zorzin2015, @thorpe2012 and @caraher2016 also related recording strategies with the sociopolitical and economic circumstances under which archaeology operates by problematizing the means and pressures for increasing efficiency as driven by capitalist mentalities and profit motives.
Others including @edgeworth2003, @goodwin2010 and @batist2021 similarly investigated how archaeological meanings are negotiated within situations of unequal understanding and hierarchical rank, and through the implementation of mediating physical and conceptual tools. 

The notion of capta situates archaeological sense-making in relation to goal-oriented apparatus of knowledge production, through which information is assembled and applied to form more coherent knowledge.
Re-framing data as capta therefore involves highlighting the targeted and reasoned approach at the moment of the archaeological encounter by people wielding physical and conceptual tools that hold their own affordances and limitations, whereas the more prevalent notion of data involves a more passive experience whereby material is swept up in its raw state and granted purpose and meaning during subsequent phases of analysis.^[This may relate to an additional meaning of the similar term "capture," which is primarily associated with generating photographic images [@richards-rissetto2019], but which is also commonly applied to describe other tactical acts of sensing, such as technical drawing [@morgan2018; @morgan2021], photogrammetry [@waagen2019; @olson2013], remote sensing [@crutchley2018], and use of digital theodolites [@mcpherron2005; @martinez-del-pozo2013], all of which involve live processing of visual cues to create useful images, thereby situating acts of observation within targeted and systematic analytical protocols and systems set up to support them.]
This aligns with Wylie's [-@wylie2010: 316] conception of archaeological knowledge construction, which considers how archaeologists recognize particular aspects of an object as meaningful based on the knowledge and understanding that they accumulate during their lived experiences, and design systems for capturing and describing these features in ways that conform to their understanding of their relevance and value.
In other words, the application of prior observations captured through data amounts to a reconciliation between the circumstances of their creation and the potentials that they afford [@wylie1989; @wylie2017].

This contributes to a view on data as mediating devices that serve to connect chains of pragmatic activities, and therefore operate as discursive media that relate different sociotechnical situations.
In other words, archaeological data are documentary records that enable research to be extended across time and place, and to be carried out in a collaborative manner.
The media upon which data are inscribed enable direct experiences with objects of interest to be shared and acted upon in alternative research contexts.
Moreover, archaeologists rely on physical and informational infrastructures, and establish organizational practices, to normalize the information that they produce and to enable these records to be accessed, understood, and put to practical use.
Archaeological data can therefore also be understood as discursive devices that enable work which relies upon various methodologies and theoretical outlooks to converge, and which help stabilize and legitimize archaeological knowledge.

This discursive notion of archaeological data is well represented in prior discussions of how archaeologists produce knowledge.
@hodder2000 experimental techniques of mediating and transmitting information at Çatalhöyük are particularly noteworthy.
Building on his recognition of the hermeneutic relationship between theory and practice, Hodder developed ways to render them more explicit: finds specialists and analysts were encouraged to participate in site tours to gain a more intimate understanding of the objects they would be working with and to obtain insights from those responsible for recovering the materials in the field [@hamilton2000]; field notes and sketches were posted in common areas, with open invitations to comment and respond with alternative perspectives [@berggren2015: 437]; excavators, who used tablet computers to enter data directly into the database, were able to access analytical findings to inform their work [@taylor2015; @taylor2018; @berggren2015]; and the project's database was designed to encourage recording different outlooks pertaining to objects of mutual interest [@mickel2015b; @lukas2018].

However, @chadwick2003 [: 102-103], @lucas2012 [: 72-73] and @sandoval2020 [: 26] questioned this approach by raising concerns about the omnipresence of and confidence in advanced and potentially intrusive recording techniques, such as documenting excavators inner thoughts or formally identifying converging perspectives upon objects of mutual interest, as means of working out this problem.
@sandoval2020 [: 36-37] doubted whether the adoption of these new media was valuable in the absence of an informed method for producing them, while @chadwick2003 [: 103] pointed out that the technological systems used to capture all of these novel insights did not adequately foster a will to participate in the kinds of work it was demanding of people, while also perpetuating the traditional and hierarchical social order pertaining to acknowledging and crediting labour in archaeological projects.^[See also @beck2000 and @thorpe2012 for related insights on the impact of sociopolitical context and informed implementation of advanced excavation recording strategies, though not as explicitly related to notions of reflexivity.]
These critiques characterize the problem that reflexive strategies attempt to resolve, i.e. the entanglement of practice and theory, as impossible to mitigate, and identify the inherent situatedness of archaeological records as something that should be accepted as a fundamental aspect of archaeological epistemology rather than something that needs to be reduced or eliminated.

Lucas [-@lucas2001a; -@lucas2012; -@lucas2019] took this to heart by characterizing archaeology as a materializing process, whereby objects of interest are transcribed as information objects with the aim of constructing comprehensive archives, which are accessed by stakeholders with varied interests and who seek different kinds of value from them.
Dallas [-@dallas2015; @dallas2016a], drawing from contemporary discourse in archival science and digital curation, similarly asserted that all aspects of archaeological work necessarily constitute discursive acts of semantic negotiation, whereby actors working in different contexts reconcile their own practical needs and expectations with the motives, methods, norms, procedures, and tools that inform prior work in alternative situations or that they presume will be present in future applications.
This is informed by participation in shared experience, whereby actors obtain intuitive knowledge of the kinds of factors that might have influenced the constitution of data and a general understanding of what information will be valuable for future applications.
Although digital tools and infrastructures may support efforts to bridge discursive gaps across the continuum of practice, they are not in themselves panaceas for resolving a lack of mutual understanding across research contexts.
This has not stopped considerable efforts to develop technological solutions to what largely constitutes a social problem.

## Workflows
Workflows, particularly but not exclusively those that rely on digital mechanisms, establish disciplined ways of working and channel information along pre-formulated pathways in service of certain kinds of targeted outcomes, such as reports based on statistical and spatial distribution of archaeological finds [@batist2021: 1737-1740; @caraher2022].
To achieve these outcomes, workflows attempt to control how information is collected, organized and processed.

This involves modelling archaeological practices in abstract ways and implementing control mechanisms to ensure that the information collected in roughly textured epistemic environments (such as archaeological fieldwork) is rendered as smooth and discrete entities, as necessitated by the protocols used in digital analytical research environments.
All archaeological activities are therefore presented as generic information processes and made to operate in service of the imperatives of data management and analysis domains.
While workflows may help to produce valued outcomes, they accomplish this by restricting alternative ways of expressing archaeological knowledge that do not directly contribute to formulaic processes [@batist2024a].

Workflows are designed to simplify or standardize work processes so that they imbue a sense of scientific control over nature, whereby scientists are able to capture stable and objective statements about reality [@caraher2019].
They effectively attempt to dissolve role of the subjective observer --- who comes with her own experiences, motivations and desires --- as generic and interchangeable, thereby reducing the potential for in-depth semantic negotiation between scholar and nature.

This is valuable in the context of open science, which is driven by a desire to render research practices more transparent.
Presenting work as following standardized procedures makes it easier to document work processes as conforming to modelled behaviour and in relation to targeted outcomes [@huvila2022].
On paper, this helps data re-users make sense of data and apply them in new contexts, but in practice scientists intuitively understand that work is never actually standardized despite efforts to present them as such [@huvila2023a; @batist2024a].
This is why those who re-use data seek out additional contextual information other than what is included in formal documentation in efforts to ascertain the specific situations and circumstances that contributed to a dataset's qualities [@faniel2013: 299-301; @atici2013: 676-677; @kansa2013: 90-91; @chapman2016: 213].

Although workflows are commonly associated with digital tools, they in fact constitute a managerial modality for structuring activities and relationships and can be manifested through either digital or non-digital media, especially when paired with social and professional pressures.
For instance, when working as part of a rigid hierarchy, it can be very difficult to negotiate with one's boss, especially when under pressure to operate with great efficiency and under extreme time constraints.
In other words, when work is limited to action and reaction without potential for discursive feedback, people are made to effectively operate as machines.

This being said, digital tools do provide some affordances that make it easier to control workers' actions and limit discursive feedback.
Specifically, digital systems are useful for ensuring that data are managed according to well-defined parameters, especially in ways that are conducive to formal data integration, which enables analytical processes situated down the line to more easily ingest and use data.
Digital processes place an emphasis on rigid structures that emulate modelled behaviour, and they have enhanced ability to enforce adherence to these models through user interfaces that limit alternative behaviour out of the models' scope [@huggett2022a: 276-278].
In other words, digital media enable managers to restrict the potential for discursive interaction and limit workers' capacity to contribute their situated knowledge.
Even in cases where digital systems have been implemented with an intent of enhancing reflexivity and multivocality, these tools do not negate the impact of centralized and hierarchical power dynamics, which are the root of the problem [cf. @chadwick2003: 102-103; @lucas2012: 72-73; @sandoval2020: 26; @beck2000; @thorpe2012].

Overall, the constitution of archaeological data is clearly informed by professional norms, expectations and value regimes, which are embedded in the social and technical apparatus that scaffold archaeological knowledge production.
This paper further explores the social, practical and epistemic tensions that arise from these mechanisms, including acts of resistance against the power relations that emerge from them.