# Discussion and Conclusion
This paper articulates the sociotechnical systems that archaeologists develop and rely on to organize themselves and the information they produce.
My aim has been to demonstrate the situated aspects of archaeological data management, and, in particular, to highlight the distribution of creative agency across the continuum of archaeological practice.
I advance a pragmatic vision of archaeology, which emphasizes local circumstances, experiences, and motivations as key factors that drive scholarly communication and participation within information commons.

Overall, I found that the management of archaeological data and of archaeological labour are deeply intertwined; the systems that archaeologists have set up to help collect, organize, combine, store, share, and reuse data all operate by controlling how people work.
Moreover, I found that the technical infrastructures that archaeologists rely on are far from being asocial entities, and in fact mask collaborative commitments, or norms and expectations that govern professional relations among participating agents.
Additionally, the organizational structures that delineate roles and their corresponding rights and responsibilities significantly influence how data are structured and made valuable.
By rendering labour as a series of programmatic operations conducted by interchangeable components, database managers and project managers work together to impose control over relatively wild archaeological experiences, making their outcomes conform to standard models.

More specifically, in the workflows I observed, managers operating from a centralized position of authority decided what data to collect, how they should be collected, and how they should be processed, integrated and stored --- all in advance of and separated from the work itself.
For instance, I observed that in archaeological photography, fieldwork was brought under the domain of the database apparatus, which curtailed fieldworkers' abilities to make independent creative  decisions.
Data management systems and the formal data structures that they enforce therefore served as vehicles through which project directors centralized their control over work being done throughout the project, and allowed them to take ownership over, exploit, and redistribute the products of collective effort.
Archaeological data management should therefore be understood as management in a more general sense due to its reliance on managerial principles that enable strategic re-arrangement of agency from a distance.
These observations corroborate reflections by other researchers, including @caraher2019 and @thorpe2012, who argued that workflows transfer interpretive agency away from fieldworkers --- who must decide what to record and how to record it --- to the system's designers --- who implement the rulesets in consultation with project management.
They also support observations by @haciguzeller2021, who noted that structured data such as those that emerge from workflows constitute non-neutral and power-laden representations --- and as such, are the outcomes of decisions to satisfy particular sets of warrants, needs and desires.

At the same time, roughly textured fieldwork environments, which are where most archaeological data first emerge, are where virtually all archaeologists learn about the norms and expectations that govern how to work and how to capture data.
More specifically, experiencing fieldwork imbues an understanding that the information that archaeologists work with is generally rough, tentative, fluid, and flexible.
The common cause and culture that archaeology has maintained, which is predominantly instilled through formative fieldwork experiences, is held as a shared intuitive understanding of the bounds of epistemic behaviour [as per @knorrcetina1999].
This encourages a well-rounded and critical assessment of how individual tasks fit within broader systems of knowledge creation and drives resistance against attempts to atomize and workflow the archaeological process.
As such, while it may seem, in an abstract sense, that projects impose order on all the work that falls under their purview, archaeologists with plenty of fieldwork experience know intrinsically that, in practice, this should be more accurately described as an _attempt_ at order which is never fully achieved.
Similar undocumented acts and attitudes of resistance are prevalent throughout the discipline, and are more acutely visible once the myth of a frictionless and technologically-mediated archaeology is understood to be a _proposition_ for one possible future, rather than an inevitable next stage in the evolution of our discipline [cf. @huggett2018a; @batist2021; @opitz2021; @caraher2022; @huggett2023a].

So, despite attempts to bring extreme order to archaeological projects as concrete systems, the actual fuzzy nature of archaeological projects shines through, and often in ways that completely disrupt the carefully orchestrated workflows.
This represents an extension to Bowker's [-@bowker1994] notion of "infrastructural breakdown" --- the phenomenon whereby infrastructure becomes acutely visible during moments of disruption --- wherein I posit that when infrastructure breaks down, the social structures and cultural experiences that hold the technical apparatus together shine especially brightly.
In my case studies, the failures to control archaeological knowledge production through the imposition of concrete structures reveal the discipline's fundamental epistemic values, and demonstrate that the more things change, the more they stay the same.
