# Supplement B
This supplement contains sections of transcribed interviews referenced throughout the paper.
References are ordered by case and by the order in which they appear. Each reference has a prefix corresponding with the case to which it pertains.

## Case A
###### A1 {#sec-A1}
**Zack:** What do you consider the most valuable skill, that an archaeologist can have?\
**Theo:** I don't know, how to wield a shovel and a mattock. That's always a valuable skill.
Like be able to identify something.
Figure out what's going on, dig it, and then accurately record it.\
**Zack:** Alright.\
**Theo:** That's the...\
**Zack:** That's a series of skills.\
**Theo:** That's the essential... like the essence of archaeology.
It's just like, you don't just sit behind a desk and write little reports and stuff.
It's like, without, you can't, you can't do that without actually having dug before.
It's im-- It's important to know what the process of excavation is, in order to understand how, like, what's going on.

###### A2 {#sec-A2}
**Zack:** So uhm, can you please describe your specialization or expertise, if you consider yourself to have any?\
**Lester:** Uhm, well I've been working professionally in excavation,
excavations for about three years now so my expertise comes in in actual fieldwork rather than a specific discipline

###### A3 {#sec-A3}
**Lester:** Well, I think it's important that people come away from this not having been trained in the trench, given a pickaxe and told to dig and get on with it, you know.

###### A4 {#sec-A4}
Had a brief convo with Olivia as she was cleaning up, when the corner cam died.
I really [...] by the mic.
It was about focus, [awareness?] of one's surroundings, being in the moment and focusing on the task at hand.
Focusing on the little things helps her keep her organized.
It is an active strategy in use. She hates that although excavation is manual labour, it really requires you to actively think.
You can't just phase out --- illegible sentence.
I mentioned my tendency to compare excavation with tunnel vision, and noted how I think it is somewhat flawed.
She asked me if I played a musical instrument, and I said no, and then asked if I could relate to that.
She compared these activities in order to convey the sense of being in the moment, facing a task at hand, dealing with what is immediately in front of you, literally and figuratively, and the satisfaction of achieving one's goals and ticking off all the boxes.
She likes to set goals, for herself and for others.

###### A5 {#sec-A5}
**Lester:** So, our first week was tough.
Very, very tough.
We had a very uhh difficult trench to excavate, very hard layers that were very difficult to physically excavate.
Uhm and I can dig for a certain extent, for a period of time in quite hot weather, I'm used to this, for this is not a problem.
But I see people that have never approached this, attack it physically, really really attack it physically, and not bear in mind that this is actually really difficult.
And it's not a physicality thing, it's a, it's a thought process.
So it's uhh, yes you're physically able to excavate twenty centimeters in a day, but how are you going to feel at the end of the day?
Are you going to be able to identify the context while you're doing it?
It's better to excavate ten thoroughly than twenty in a hurry, you know?
And, but the speed will come with time.
And so I've noticed this with Morris particularly, he was quite, he's a very able archaeologist, a very good digger, uhm but physically he's changed the way he approaches things, so he won't go full-on that unclear now, and then expect to be able to do it again the following morning.
And then equally, the understanding is growing, so like contextual change, uhm, I've really struggled to try and integrate teaching into my methodologies on site, because that's not my skillset, and not what I'm used to.
But now I think we've finally figured it, I'm involving him in the paperwork a lot more, making that a part of the teaching process, a bit more.
I think it's beneficial.

###### A6 {#sec-A6}
The other cam is on Morris' head as he clears and gardens to set up a new 5x1 trench.
Comment: "it is a weird trench" (Morris).
Slightly rhomboid, not as square-angled as intended.
Morris "catching on" according to Lester after he asserted / referred to the controlled environment that we constructed.
One wall is extended 10cm out in one corner, a mistake attributed to marking the rectangle on the steep slope, lengthwise downhill.
Morris also joked that the error might be corrected by sloping the section by 10cm.
This also contributed to Lester's comment on Morris' "catching on".
He is confident enough to joke, and for the joke to be a good one, no less.
Also interesting how the work space shapes the trench.
Supplies used to delimit the trench are put on / near a rock in the corner.
A clear space devoid of rocks is needed.
Supplies placed in the corner, on the rock, mark a boundary.
They also necessitate some clearance, 0.5-1m between them and the delimited trench.
Spoil head location is in the bushiest part, where the cleared grass was placed.
More room on small side for sieve, but more land can be cleared too.
Lester is thinking about where to put the spoil heap.
My earlier notes were of passive and seemingly assumed locations.
It turns out I was correct in my assumptions pertaining to where the spoil heap would be located, and the reasoning behind its situation there.

###### A7 {#sec-A7}
**Zack:** Have you questioned any of the methods you're using? Like internally but you've been afraid to ask.\
**Jane:** I think the biggest thing that surprised me, and like now it kinda makes more sense, but I was like, I wasn't the first person to start digging, obviously Basil did first and then I kinda just like watched what he did and then I started digging, and he was so rough with like the context, like he just went at it with a triangle and then like with a pickaxe, and I was like, like I pictured archaeology like, so meticulous and slow with like a little brush, like I don't know, like I guess maybe with like bones and shit you would do that because they're more delicate, but I was like oh my god, like he's just breaking it up, what if there's something delicate underneath? Like, that really took me back.\
**Zack:** But now I see you just going through it.\
**Jane:** Yeah, yeah, now it's like, I guess cause they are\
**Zack:** What changed your mind?\
**Jane:** Cause I just realized there's like tools that have survived thousands of hundreds of years.
So it's like if they can survive that
then they can survive like triangles going through it, you know?
So might as well go quickly.
But I think that was the kind of thing at first that was like, what? This is kind of weird but okay.

###### A8 {#sec-A8}
**Ben:** But I don't, like the paperwork and all that, like I'm not like, I'm not, I'm not one to like be sitting at a desk just writing all day.
Like, I like to be in the trench, I like to be doing something physical and like engaging, right?
And I don't, like reading and like articles and like scientific research and stuff, just like, it doesn't interest me, like that much.
Even like, I have to be engaged in the topic, you know?\
**Zack:** Yeah, yeah.
I feel like you and Theo have a lot in common.\
**Ben:** I think so, yeah.
Like Theo describes himself as like I dig holes, and I'm like yeah, I can relate to that, man.
Like I dig holes too.

###### A9 {#sec-A9}
**Zack:** So umm, I guess I've already got your bio and all that.
But I'm wondering if you could reiterate your overall objective of your work.
I mean how your work contributes to this project.\
**Theo:** Umm, the objective of my work\
**Zack:** Or of your contri-- or of what you're doing here.\
**Theo:** It's to dig holes. Dig holes.\
**Zack:** So maybe a way to get a better answer, can you tell me about the current season and what your current plans are, or have been?\
**Theo:** For this season I've been digging a big hole.
Yeah, we aim to finish it, but I doubt we will.

###### A10 {#sec-A10}
Liane got in to plan the micromorph sampling.
She and Lauren looked at the section, pointed at levels, indicating which should pertain to each context.
Repositioned myself to better observe Liane. She is actually 'carving' (my own term, not hers) a block using a flat metal instrument, I believe the metal inside of a trench handle, which is embedded within the head, that was broken or taken off illegible.
Liane returned back with mallet and chisel.
Others had to get out of the way so she could proceed.
Liane also applied gypsum plaster to the micromorph sample.
Apparently this one took longer to define than the others.
She will return tomorrow to chisel out the sample and apply gypsum plaster to the internal face, and label it all up for further analysis by Alfred.
It needs time to dry, for now.

###### A11 {#sec-A11}
Small discussion with Lauren and Ben about the tools that archaeologists use, after I picked up the triangle and repeated a tidbit I heard from Basil that it is supposed to be used for wallpaper stripping.
Ben noted that they were extremely useful, and was surprised that it was not used primarily for archaeological purposes.
Also that they are exclusively used in the region due to the rocky and baked soil.\
She then demonstrated how difficult it is to use a trowel in thus environment by showing how it would be typically used on a particularly flat surface.

###### A12 {#sec-A12}
Theo changed sections, and I found the illegible word that followed very interesting.
After hammering in the rebar and vertically aligning the string, it is only level at a point that is higher than the rebar.
He told me to go grab the other rebar in the corner, though it is massive.
Tried hammering it in, but it was clear that it would get blown over by the wind.
I offered to hold it steady but instead he told me to rummage in his bag and find a nail and masking tape.
He attached the long nail to the rebar, adding 4-5 inches to its length.
He then proceeded, with my assistance, to tie the string around the nail, clip it on securely, and secure the line down with a rock.
Regarding securing the line down with a rock, this was a challenge for me yesterday, as well as when I did this for the earlier section this morning.
I needed to find the right kind of rock, which was not too big, but still dense.
It needed to be not too rough, but with sharp angular corners.
This was never made explicit; after two failed attempts, first with a large rugged rock, and then with a smaller, less rugged rock, he picked up one and gave it to me, saying "something like this".
I wound the string around it, leaving some slack, and then positioned the rock in a way that would render the line taut, by rotating it or securing it around others.

###### A13 {#sec-A13}
Came over with Theo, Maddie and Gwen present.
Maddie set up level strings around the trench \
Theo asks Maddie to unfold long tape measure (referred to as tape).
Then asks to get in, hops in.
Unfurls rolled out tape measure, aligns it along north edge, top. They have selected the north section to draw.\
One square on graph paper is 10cm in real life.
I offer my clipboard.\
"How deep is your trench?", illegible it to the string.\
"What corner is that?" "Southeast corner."\
"So that is your eastern section?" "Yep."\
Refers to line on paper: "So this is your stable line."\
"I always start from the top"\
Every 10cm, the distance from the ground to the line level is measured.\
Now they alternate.
He holds the tape 10cm lower than before, dictates the distances to the line.\
Actually, he holds it to the edge of the unit, not the next 10cm (my mistake).\
Then Maddie connects the dots on her page, as per Nat's instructions.
She does a repeat line, like you would in a sketch, and he says "no, you want a solid line".\
Does this again for the next unit.
Gets his scale ruler out to draw the boulder, which interrupts the section in the corner.
I did not see how he used it, exactly.
It looks like an unfilled portion, no texture at all.
It has been labelled as "boulder", written inside.\
Dot-dash line drawn to indicate "extrapolated" drawings, used to draw parts of the section where bedrock has been hit.\
Then they do the base.\
"It this bedrock?" "Yes."\
"Then you can do as I did here"\
Dot-dash line drew up to the boulder, as on the base at its edge.\
Dot-dash line then drawn on the corner, to complete the "frame".\
Asked her what she thought.
To her, it is exactly what is there.
She owes this to her being a visual person, is sure she can easily repeat by herself.\
Theo then teaches the symbols, patterns used to represent materials, soils, sediment types.\
He notes his own conventions as opposed to general convention, to draw pottery and other finds that stick out of the sides.\
Also must draw in only the big rocks.
After some discussion concerning what counts as such, Theo demonstrates which ones fit with his description or conventional ways to define such rocks, by pointing out which ones fit those criteria.\
Another layer, just then drawn.
It is "wedged" past the dot.
Dangles under the boulder, since it is somewhat extrapolated.
This is not a complete line, only sticks out of that vertical dot-dash under the boulder.\
Then Theo offers the tape to Gwen, who tells the measurements at the line.
Theo places his hand at the base to support the tape, since she is slightly unsteady, and she can not bend over to look at how the bottom aligns with the layer's edge.
Theo also uses this to control where the edge is defined.\
Now they're drawing the rocks.
First is actually a negative impression, where a rock presumably fell out.
Theo says to typically draw three points.
However in this case he suggests four to be sure.
He then says to just 'eye in' the shape of the lines that connect them.\
She does so, then indicates that her lines are less well-defined than before, in a hesitant tone.\
Theo procures a pencil sharpener, and sharpens it himself.
He is very careful, after some big twists, does a few smaller twists, pulling it out and inspecting the tip each time.\
Jess now measuring points on rocks on her own.\
Theo says that you can use any number of points, depends on how comfortable you are, and depends on the rock, but he prefers to use less points and then "draw it all in" by eye.\
After he packs his bag to go back, she traces over her solid lines, defines them more strongly using her sharpened pencil.
Theo offered to come back in an hour, but Maddie insists it will take less than that.
Theo agrees.

###### A14 {#sec-A14}
Typical script:\
"At x on the horizon, it's y down"\
Followed by an acknowledgement.\
Sometimes a novice asks "from what?", or "from the east end?", or "from the line?", but once it is clarified that the reference point remains fixed, then they instantly understand how the whole system works.
It is all about two people, working in tandem, with a commonly understood system of communication that goes along a shared reference point.
I noticed such an "ah-ha!" Moment when Theo was teaching Morris how to do this.\
We then went to redacted trench ID, where I went down to bring some equipment down the hill, while Theo and Jane started in redacted trench ID.
Jane is doing measurements, while Theo plots the points.\
Jane seems very comfortable in her trench, much more than Alice yesterday.\
Theo is able to communicate with her, ask her questions.
She also refers to her sediment description on her contexts sheets so that Theo can articulate ? them more appropriately.
He asked whether what they just did was the hearth and she said "no, it's the black-brown stuff above the hearth".
He then wrote something like that down on his drawing.
He also showed her the connected dots and asked her "does it look something like that?"
And she answered that it does.\
Some other common lines:\
"Does it go up/down left of that rock?"\
Basically a series of relations among entities, which are described in terms of actions that they take.\
They "hit the section", "rise/fall", "plateau", "flatten out", etc.
In any case, the activity of the delineations is energized.
Really, the focus is on the line, or the interface.
The interface moves in relation to the reference points, that is.
Moreover, it is accepted that such activity is unclear or blurry, and that extreme precision is pointless.

###### A15 {#sec-A15}
I asked Lauren about the placement of her line and tape measure, and she told me that it is not due to the present circumstances - she picked that up from her first excavation, and has been doing drawing in such a way ever since.
There are several practicalities involved.
First, she finds it beneficial to measure both upward and downward relative to the line.
This is particularly useful in deep trenches.
The line is placed in an arbitrary position, where there are few rocks at the corner, so that nails can be hammered in easily.
After one section is drawn, she can then remove one of the nails, pivot the string around so it is on the other face of the pivot corner, and secure it easily there.
Then she must check the level on the line, before proceeding with her measurements.
She notes that setting up the string is definitely the most time consuming, or effortful, part of drawing.\
This seems to have several advantages over Theo's way of doing things, in terms of relative ease.
There was definitely a lot of effort put into securing the line, making sure it is taught, etc, since he relies on shaky rebars, strings tied down with rocks, and an above-surface line that blows in the wind or is at risk of being tripped over.
However, he uses the local datum as the reference point, and does not have to measure the depth of the line.
This additional set of numbers and calculations might be an impetus for his aversion to Lauren's method, but I have not asked him about it yet.

###### A16 {#sec-A16}
I will now observe Theo and Alice draw the sections for trench redacted trench ID.
No one else is here, and Theo expressed some confusion regarding what is going on in this trench.
Moreover, Basil can not find the paperwork for redacted trench ID, he is on top of the hill at either redacted trench ID or redacted trench ID, and Jane is resting back at the dig house.
So it should be interesting to see how Theo's drawing pans out with Basil's expectations.\
He is currently setting up the illegible word, string and line levels. It is extremely windy, so it is a bit of a challenge.
As before, the string and tape measure are clipped to the rebar that are staked into the ground at the corners.
The line is on the south section.
Because of the slope, much of the line is higher than the ground and this causes the wind to shake it all over the place.\
Alice on the big boulder in the southeast corner.
Theo on the north side, with graph paper, taped down to his clipboard with bandaids.
Alice calls out numbers to him as he asks them down.
They called for my help for a moment because it was too deep for Alice.
Upon hearing the elevation of the base at 1.5m along the edge, Theo illegible word and said it is illegible word too deep, and that he would need another sheet of paper.
This wind is going to make that horrendously difficult.
So they re-prioritized, and limited their scope to the upper part that would fit on the page.\
I was interrupted, since my assistance was needed.
I had to hold the tape illegible words numbers to Theo.
It was also challenging since no one who actually knows the material was actually present to interpret the stratigraphy.
Basil then came by, acknowledged that this would not be very effective due to the wind and unfamiliarity with the trench, and instead Theo, Alice and I spent the rest of the day lugging equipment down the hill.

## Case B
###### B1 {#sec-B1}
**Zack:** Or are there certain competencies or skills, or like, just mindsets needed?\
**Chris:** I think, yeah, I mean I always feel like the mindset has to be like, I will go and try to make this, make this work as best as possible.
Like kind of come up with those convenient sort of work around, like I found a way.
Here's like, here's a unclear, like something from the national geo like geological survey, where I can just plug in, it will plug in some coordinates that will spit uhh spit out the correct UTM coordinates.
Had to do it one by one, I think there's a way of doing it on a mass level but I just haven't been bothering to do that yet because I only need to do really one at a time, that's-- and then, you know that I can plug it all into GIS anyway and then Rufus can just flip the switch and just turn it to UTM, so it's fine.
Umm. That, I think you're just sort of like work with what you're, or kind of work with what you've got.
I mean like sort of our sieves are sort of an example of that.
The original sieves were sort of like here's what we got, we have no money, let's just get some like little/electrical ties and piece of janky sieve we found and just make it work with some dowel.
Like you know, it's super cheap.
It's sort of like a unclear sort of like on the fly, and you just kind of have, gonna have to do that to be super flexible.
And it's sort of like, that's my view of technology.

###### B2 {#sec-B2}
**Zack:** Can you just take a minute to explain it to me?
The document that you made there?\
**Oliver:** So, started by drawing just the outside of the square, these lines here.
Then inside, with these walls, you know, focusing on getting the articulation on this centre wall where the pit is.
Umm, so kind of getting the bigger stones, umm just indicating that we think there is a wall there, and then capturing the general outline of the pit, umm, they excavated, and getting a little bit of definition as far as how steep it is.

###### B3 {#sec-B3}
**Zack:** Can I get a brief shot of the page, what you're writing there?\
**Chris:** Sure.\
**Zack:** Yeah, it's just basically a photo log.\
**Chris:** Yeah, just a photo log, just making little notes, and then I transfer it to a, like a spreadsheet.\
**Zack:** You keep track of the photo number? Like the file name?\
**Chris:** Yeah, so everything, so what I do is I copy like a reference to the image file name in that spreadsheet, and every photo, and each photo is labelled like redacted context ID\_P1, \_P2, like for each, each, each umm stratigraphic unit.

###### B4 {#sec-B4}
**Rufus:** Okay, so if we can have just nobody standing on this line, just cause of the shadows kicking over So can you come on this side?\
**Zack:** Sure, sounds good.\
**Zack:** So the shadow was to, the shadows--\
**Rufus:** So the basic thing with the shadows is that, if my shadow is right here, and I take a picture, and then I take a picture over here and my shadow has moved, the photogrammetry can't find similar points of interest.
Because it's looking for that shadow but then suddenly that shadow's in a different position in another picture and as far as the alignment goes it's a big mess.\
**Zack:** Ok.\
**Rufus:** So I always have to keep an eye on my shadow.
Obviously grasses and things like that create a problem because they're really long and skinny and they can move one way or the other.
And again, it's for points of emphasis, for similar features on multiple pictures.\
**Zack:** Ok.\
**Rufus:** So when you take your pictures you have to make sure you uhh, have enough, you do it systematically and you do it so you have enough overlap, so you know like like 30% per picture.
I'm just gonna move things out of the way a bit.\
(moves some buckets)\
**Rufus:** So the idea is you start farther out, you take pictures around. And then you go in, take pictures in a circle, and then you go over the object and take pictures that way.\
**Zack:** Alright.\
**Rufus:** So that's the, that's the goal here.\
**Rufus:** Then after you do the big circle, the inner circle, you just kind of go over the top and take some like random pictures to make sure you have some extra coverage on the unit you wanna-- to make sure you have coverage\
**Zack:** So, when you process these, do you systematically organize them?\
**Rufus:** Uhh, it brings them it and it automatically aligns them.\
**Zack:** Oh.\
**Rufus:** But the thing, the time consuming part uhh they call masking, basically you're cropping out things that you don't want in there.\
**Zack:** Yeah.\
**Rufus:** That takes some time. But if you do that right and run it it'll do a good run.

###### B5 {#sec-B5}
**Rufus:** Umm, but there are online places where you can go to upload these things, and uhh my work with Mark, quote a bit at uhh at a co-worker's project in another site, umm looking at his information and data, he's put a lot up on file sharing sites, like uhh, I'm trying to think of the name of some of them, I can't, but there are places where you can upload 3D models and type a couple of key words into it, go to this place, google it, google Pompeii and you can see these models unclear.\
**Zack:** Uhh one comes to mind, it's called SketchFab.\
**Rufus:** SketchFab, that's it.\
**Zack:** Is that it\
**Rufus:** Exactly.\
**Zack:** Okay.\
**Rufus:** Yeah, SketchFab.\
**Zack:** Uhh and, do you find that's being used extensively by archaeologists?
Or just uhh, or is, do you get a good DOI out of it?
Or is it sort of that, would it support this, what you want out of it?\
**Rufus:** Uhh I think it's more of a, kind of just a, I mean it's almost like an Instagram of, of 3D models.
You can, you have your profile set up, you can type key words into it, and just throw it up there.\
**Zack:** Mhm.\
**Rufus:** Umm the, uhh, the, the ability to manipulate, measure, umm isn't as great as you would want to see unclear or whatever, but it's there, it's useable, it's umm, it's more of a, it's more of an aesthetic thing like hey, check this out,\
**Zack:** Yeah.\
**Rufus:** this is what we're doing.

###### B6 {#sec-B6}
**Liz:** We took out, we uhh, moved all the vessels off of a floor in one room.
And what we saw were these clusters of certain types of artefacts on one side of the room.
And then we saw a totally different, not totally different, but a unique set of artefacts on the other side.
So this shows us that in the southern end, my theory, right, is that there's umm a shelf on a wall that falls, right.
And so that part of the room was used for that, for storing of those types of vessels.
The other side, totally different.
So, and thinking about how you want to assess the stratigraphic unit in of itself, as, as, sort of, a component, or umm a sort of final component of a bunch of smaller groups, and sort of informs that.\
**Zack:** So how did you control for that?\
**Liz:** So we took GPS points by cluster of artefacts, which were defined based on their spatial relationships to features around them.
So we didn't grid it.
I think gridding is sort of, creates arbitrary boundaries.
So we wanted to create boundaries that could reflect whatever use the room had in antiquity.
So we did that.
And then collected artefacts, umm, and plotted them by cluster.

###### B7 {#sec-B7}
**Rufus:** Anyway, uhh you go individually photo by photo, and then you just crop out the stuff that you don't want to be included in the processing.
If you don't do that then the model can take eight to twelve hours and then crash and it's a, it's a big mess, just cause it's looking for all those points across that space.
So then I had to, kind of, refining your environment will allow you to, to process something and get pretty, pretty clear.
So then what we do, obviously this is not a uhh, so in previous seasons you uhh, eighteen for example, taken that model, this is just a report from last year.
We take that model and then export it to geo-referenced ortho-TIFF, we then take that and create top plans based on that.

###### B8 {#sec-B8}
**Liz:** Okay.
So umm, when we talk of the form we think primarily about soil and relationships, so everything on the top is filled out, umm dealing with what types of soil are we dealing with, and how does it compare with what's going on around it.
And of course the Harris matrix.
All of the elevations and coordinates are locked in a computer system so umm all those go in later, with the end of the unit, umm once we get all that data, which is all used in the GPS.\
**Zack:** Mhm.\
**Liz:** Umm, uhh.
I like to include as much detail as possible on procedure, so right here and a bit on the back.
Umm so describing the type of sieve, umm we have 5mm sieves here, umm and then of course water sieving and then finds recording as we go, so make sure that nothing--\
**Zack:** So you have a water sieve, but not here?\
**Liz:** Uhh we don't actually have an operational one right now but we do umm, we collected about 10 bags of soil last year that we need to water sieve that are just waiting\
**Zack:** But you also redundantly do it in the database, I presume?\
**Liz:** Yeah.\
**Zack:** So you have both parallel records then?\
**Liz:** Exactly. Yeah.
The goal is to have them match 100%, so the scans of these will be matching.\
(flips sheet over to back side)\
**Liz:** Umm, and then our description is for discussing in more detail the relationship between the soil and the inclusions in the matrix that we didn't see before, umm what's different about it, how is it umm, what is its relationship with what came before, what's its relationship with what we're umm finding and revealing as we go.
Umm, also sort of exploring, umm, the relationship to the different features, so walls, things like that, umm installations.\
**Liz:** And then procedures.
So like discussing types of tools used, umm order, or sort of method and direction of excavation, umm those kinds of things, all go on the back.\
(flips sheet over to front side)\
**Liz:** Umm, where a lot of the sort of interpretive and those kinds of things.
So like for like the labelling of units, I give them something that's very very vague, that purely describes what we're seeing, rather than interpreting what it means, so just soft fill on that side of the trench, for example.
And then in the actual, in my trench notebook, that's where I put all of those thoughts, umm, in more detail.\
**Zack:** Can you show me your trench notebook, briefly?
You don't have to go into great detail into what's in the notes, but an overview, I guess.\
**Liz:** Yeah, so, we're excavation unit 20.\
**Zack:** This is the front page?\
**Liz:** This is the front page.
Umm so here are umm the coordinates of the uhh, the northing, easting and elevation of the corners.
So those obviously aren't gonna move so those are permanent.
All recorded in UTMs in 36 south.
Umm, the opening elevation at the centre.
So really umm, the foundation for how we started.
And then sort of a brief sketchy Harris matrix that keeps evolving over time.\
(turns page)\
**Liz:** This is just a sketch plan of features in the trench, so that I can keep the numbers straight, and keep referring back to it.
Umm and then just day by day notes, including things such as who's actually working in the trench today, uhh what's the weather like, those kinds of things.
If someone comes to visit, I write that down, umm it's just a way to sprint of jog your memory to sort of remember which day you're talking about.\
**Zack:** Do you write in prose form?\
**Liz:** I write it in prose form, mhm.
With some bullets, there are bullet points and things like that, especially for things like points taken, things like that, umm sketchy little things like that about what the trench looks like at different points throughout the day, just to keep reminding myself about what's going on.
Umm and then interpretation, so what can it possibly be, what's its possible relationship.
Even if we don't know it yet, I'll let those come out here.\
**Zack:** So really, so that summary, at the top of the sheet?\
**Liz:** Yeah, in more detail, and sort of describing-- so this for example, umm I'm not going to call it a floor on this sheet, I'll call it a floor here.\
**Zack:** It's more open-ended I guess?\
**Liz:** Because it's more, yeah, it's more sort of postulating what could be true and what could not be true. Umm, yeah.\
**Zack:** And do you start, let's say you're starting a new trench, do you start a new notebook?\
**Liz:** Yeah. So each trench gets its own.\
**Zack:** Do you, are these integrated into the database?
Are they scanned or integrated into the database at some point? Or cross-referenced at all?\
**Liz:** They're scanned.
Umm, as far as I know they're not cross-referenced with any particular points in the database.
Umm, our database isn't operating yet.

###### B9 {#sec-B9}
**Zack:** How, it's great umm.
Have there been any specific or significant events or, events or people or uhh uhh significant significant events or people that serves uhh umm uhh changes that that have guided you in this direction?
Uhh towards, in towards archaeology or that have sort of pushed you into archaeology or into the application of digital methods in archaeology?\
**Chris:** The application of digital methods?
I mean there's no, no one or no one thing in particular.
It's sort of just my own umm thinking about the you're kinda thinking about like what would be most effective and most most sort of streamlined umm in in in terms of in terms of recording, tools used, things like that.
Umm and sort of like I asked around, I talked unclear, again, it's mostly under my own sort of initiative umm.

###### B10 {#sec-B10}
**Zack:** does the, does the use of such technologies effect the ways that archaeologists work?\
**Liz:** I mean I think so.
I think it allows you to either rely on it, and so you say well ArcGIS will tell us so we'll just leave that, we'll plat that in, it'll be fine.
Umm but also, in a, in a good way and in a bad way, right?
In a, like, let's speed up this process.
And also in a like, so maybe I can be a little bit, you know, less meticulous in the field or something.
Umm because of, this is what ArcGIS can register.
Umm it can't register finer than that, maybe, or something like that.
Umm so I think if it's the only tool that you're using, it certainly would change uhh, yeah it would change the sort of decisions that you make, yeah.
